backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: state
    label: State
    folder: cms/stores
    create: true
    editor:
      preview: false
    widget: object
    field:
      - { label: 'State', name: 'state', widget: 'string' }
      - name: city
        label: City
        widget: object
        field:
          - { label: 'City', name: 'city', widget: 'string' }
          - name: store
            label: Store
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Address', name: 'address', widget: 'string' }
